feat(Iron Tanks)Add new 3 new Tanks
GTNewHorizons/Irontanks pull request #4
Opened 2020-09-27 19:27 UTC by Dream-Master

rename Emerald Tank to Aluminium Tank
change the recipe and textures
add new Stainless Steel, Titanium and Tungsten Steel Tank 120, 256, 512 Buckets
put recipes into code

2020-09-27 22:41 UTC, bartimaeusnek requested changes
The recipes are completly unreadable.

2020-09-28 05:52 UTC, Dream-Master commented
If you have a better idea to add it feel free to make a suggestion. I try to make it more readable but I failed.

2020-09-28 20:14 UTC, repo-alt commented
They were just as unreadable before?

2020-09-28 20:31 UTC, mitchej123 approved these changes

2020-09-29 04:53 UTC, merged